version: '3'
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - "/docker/config/jdownloader:/config:rw"
      - "/srv/mergerfs/pool1/downloads:/output:rw"
      - "/srv/mergerfs/pool1/media/Anime:/anime:rw"
      - "/srv/mergerfs/pool1/media/Documentaries:/docs:rw"
      - "/srv/mergerfs/pool1/media/Movies:/movies:rw"
      - "/srv/mergerfs/pool1/media/Shows:/shows:rw"
      - "/srv/mergerfs/pool1/media/Sports:/sports:rw"
    restart: "no"
    labels:
      - "diun.enable=true"