version: "2"
services:
    ytdl_material:
        environment: 
            ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
            ytdl_use_local_db: 'false'
            write_ytdl_config: 'true'
            UID: 1000
            GID: 100
        restart: always
        depends_on:
            - ytdl-mongo-db
        volumes:
            - /docker/data/youtubedl:/app/appdata
            - /srv/mergerfs/pool1/media/YouTube:/app/audio
            - /srv/mergerfs/pool1/media/YouTube:/app/video
            - /docker/config/youtubedl/subscriptions:/app/subscriptions
            - /docker/config/youtubedl/users:/app/users
        ports:
            - "8998:17442"
        image: tzahi12345/youtubedl-material:latest
        labels:
            - "diun.enable=true"
    ytdl-mongo-db:
        image: mongo
        logging:
            driver: "none"          
        container_name: mongo-db
        restart: always
        volumes:
            - ./db/:/data/db
        labels:
            - "diun.enable=true"