version: "3.1"
services:
  assetgrid:
    image: assetgrid/assetgrid
    container_name: assetgrid
    volumes:
      - assetgrid-data:/docker/data/assetgrid
    ports:
      - 82:8080
    labels:
      - "diun.enable=true"

volumes:
  assetgrid-data: