---
version: "2.1"
services:
  healthchecks:
    image: lscr.io/linuxserver/healthchecks:latest
    container_name: healthchecks
    environment:
      - PUID=1000
      - PGID=100
      - REGENERATE_SETTINGS=False #optional
      - SITE_LOGO_URL=https://healthchecks.io/static/img/logo-full-ua.svg #optional
    volumes:
      - /docker/config/healthchecks:/config
    ports:
      - 8050:8000
    restart: unless-stopped
    labels:
      - "diun.enable=true"