version: '3.5'

services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    ports:
      - "7070:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - /docker/config/scrutiny:/opt/scrutiny/config
      - /docker/config/influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/nvme0n1"
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
      - "/dev/sdd"
      - "/dev/sde"
      - "/dev/sdf"
      - "/dev/sdg"
    restart: unless-stopped
    labels:
      - "diun.enable=true"
