version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3030:3000
    volumes:
      - /docker/config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock # optional
      - /srv/mergerfs/pool1:/pool1
    restart: "no"
    labels:
      - "diun.enable=true"