version: "3.7"

services:

  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    #labels:
    #  - com.centurylinklabs.watchtower.enable=false  #exclude from watchtower auto-update
    environment:
      - PUID=1000  #UID of a user on your system
      - PGID=100  #GID of the user group on your system
      - TZ=America/Toronto  #your linux timezone
      - F2B_LOG_TARGET=STDOUT
      - F2B_LOG_LEVEL=INFO
      - F2B_DB_PURGE_AGE=180d
#   These lines can be used for email notifications if required
#      - SSMTP_HOST=smtp.example.com
#      - SSMTP_PORT=587
#      - SSMTP_HOSTNAME=example.com
#      - SSMTP_USER=smtp@example.com
#      - SSMTP_PASSWORD=
#      - SSMTP_TLS=YES
    volumes:
      - /docker/config/fail2ban:/data
      - ./data/compose/42/data/logs/:/var/log:ro  # This line allows fail2ban access to read the NPM logs
      #- /var/log/auth.log:/var/log/auth.log:ro  #example entry for allowing access to any other system logs, adjust as required.
    restart: unless-stopped