---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Toronto
    volumes:
      - /docker/config/sonarr:/config
      - /srv/mergerfs/pool1/media/Shows:/tv #optional
      - /srv/mergerfs/pool1/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    labels:
      - "diun.enable=true"