services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of 
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    tinyauth:
      container_name: tinyauth
      image: ghcr.io/steveiliop56/tinyauth:v3
      restart: unless-stopped
      environment:
        - SECRET_FILE=/secret.txt
        - APP_URL=http://tinyauth.example.com
        - USERS=user:xG?(T+^VHKZ+[MJE}5[Kik/* # user:password

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    labels:
      - "diun.enable=true"
