version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "0:0"
    ports:
      - 2323:8080
    volumes:
      - /:/data
      - /docker/config/filebrowser:/config
      - /docker/config/filebrowser:/branding
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
    labels:
      - "diun.enable=true"