---
version: "2.1"
services:
  changedetection:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: changedetection
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Toronto
      - WEBDRIVER_URL=http://browser-chrome:4444/wd/hub
      #- BASE_URL= #optional
    volumes:
      - /docker/config/changedetection:/config
    ports:
      - 5000:5000
    restart: unless-stopped
    labels:
      - "diun.enable=true"
    
  browser-chrome:
    hostname: browser-chrome
    image: selenium/standalone-chrome-debug:3.141.59
    environment:
        - VNC_NO_PASSWORD=1
        - SCREEN_WIDTH=1920
        - SCREEN_HEIGHT=1080
        - SCREEN_DEPTH=24
    volumes:
        # Workaround to avoid the browser crashing inside a docker container
        # See https://github.com/SeleniumHQ/docker-selenium#quick-start
        - /dev/shm:/dev/shm
    restart: unless-stopped
    labels:
        - "diun.enable=true"