version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:100
    group_add:
      - "106"
      - "44"
    network_mode: "host"
    privileged: true
    volumes:
      - /docker/config/jellyfin:/config
      - /docker/data/jellyfin:/cache
      - /srv/mergerfs/pool1/media/Anime:/anime:ro
      - /srv/mergerfs/pool1/media/Documentaries:/documentaries:ro
      - /srv/mergerfs/pool1/media/Movies:/movies:ro
      - /srv/mergerfs/pool1/media/Shows:/shows:ro
      - /srv/mergerfs/pool1/media/Sports:/sports:ro
      - /srv/mergerfs/pool1/media/YouTube:/youtube:ro
    ports:
      - 7096:8096
    restart: "no"
    devices:
      # VAAPI Devices (examples)
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    labels:
      - "diun.enable=true"
  jellyfin-vue:
    image: jellyfin/jellyfin-vue:unstable
    container_name: jellyfin-vue
    stdin_open: true
    tty: true
    ports:
      - 7097:80
    restart: unless-stopped
    environment:
      - DEFAULT_SERVERS=http://192.168.0.2 # optional
    labels:
      - "diun.enable=true"
### Jellyfin Segment Editor - Media Segments management made easy
### Also available as tiny app for your desktop
### Project: https://github.com/endrl/segment-editor#jellyfin-segment-editor
  jellyfin-se:
    image: ghcr.io/endrl/jellyfin-se:latest
    container_name: jellyfin-se
    ports:
      - 7098:80
    restart: unless-stopped
    labels:
      - "diun.enable=true"