---
version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Toronto
      - AUTO_UPDATE=true #optional
      #- RUN_OPTS=<run options here> #optional
    volumes:
      - /docker/config/jackett:/config
      - /data/jackett:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    labels:
      - "diun.enable=true"